apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: monitoring-kube-prometheus-prometheus
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: 9090