apiVersion: apps/v1
kind: Deployment

metadata:
  name: eks-dev-deployment-app
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: eks-dev-deployment-app

  template:
    metadata:
      labels:
        app: eks-dev-deployment-app

    spec:
      containers:
        - name: eks-dev-deployment-app

          image: IMAGE_PLACEHOLDER

          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "200m"