name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t app .

      - name: Push to ECR
        run: |
          echo "Push image to ECR"

      - name: Update Kubernetes Manifest
        run: |
          echo "Update image tag"