name: Terraform provisioning

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'terraform/**'

  workflow_dispatch:
    inputs:
      action:
        description: Terraform action
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy
      confirm_destroy:
        description: Type DESTROY to confirm
        required: false
  
permissions:
  id-token: write
  contents: read
#env:
#  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: >-
      ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'develop' && 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine Environment
        id: env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Terraform Format check
        working-directory: terraform/environments/${{ steps.env.outputs.env }}
        run: terraform fmt -check -recursive

      - name: Terraform Initialization
        working-directory: terraform/environments/${{ steps.env.outputs.env }}
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/environments/${{ steps.env.outputs.env }}
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        working-directory: terraform/environments/${{ steps.env.outputs.env }}
        run: terraform plan -out=tfplan
      
      - name: Terraform Apply
        if: github.event_name == 'push' || github.event.inputs.action == 'apply'
        working-directory: terraform/environments/${{ steps.env.outputs.env }}
        run: terraform apply -auto-approve tfplan
      
      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy' &&
            github.event.inputs.confirm_destroy == 'DESTROY'
        working-directory: terraform/environments/${{ steps.env.outputs.env }}
        run: terraform destroy -auto-approve
      
      #- name: Upload Plan
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: terraform-plan
      #    path: terraform/environments/dev/tfplan