name: Terraform provisioning

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/environments/dev
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan

      - name: Terraform Destroy
        working-directory: terraform/environments/dev
        run: terraform destroy -auto-approve