name: Destroy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: payment-dev-eks-cluster

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Configure Kubeconfig
        run: |
         aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $CLUSTER_NAME

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Delete Ingress
        run: |
         kubectl delete -f kubernetes/ingress \
           --ignore-not-found=true

      - name: Delete Application
        run: |
          kubectl delete -f kubernetes/apps \
            --ignore-not-found=true
      - name: Wait for ELB Cleanup
        run: |
          while [ $(aws elbv2 describe-load-balancers --query 'length(LoadBalancers)' --output text) -gt 0 ]
          do
            echo "Waiting..."
            sleep 30
          done

      - name: Remove Addons
        run: |
          helm uninstall aws-load-balancer-controller -n kube-system || true
          helm uninstall ingress-nginx -n ingress-nginx || true
          helm uninstall monitoring -n monitoring || true
          helm uninstall argocd -n argocd || true
          helm uninstall cert-manager -n cert-manager || true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve